[package]
name = "Snake"
version = "0.1.0"
edition = "2021"

[dependencies]
rand = "0.9.0"
serde = { version = "1.0.104", features = ["derive"] }
serde_json = "1.0.48"

[dependencies.sdl2]
version = "0.37.0"
default-features = false
features = ["gfx", "ttf", "mixer"]
